// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XCONVHW_H
#define XCONVHW_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xconvhw_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XConvhw_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XConvhw;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XConvhw_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XConvhw_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XConvhw_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XConvhw_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XConvhw_Initialize(XConvhw *InstancePtr, u16 DeviceId);
XConvhw_Config* XConvhw_LookupConfig(u16 DeviceId);
int XConvhw_CfgInitialize(XConvhw *InstancePtr, XConvhw_Config *ConfigPtr);
#else
int XConvhw_Initialize(XConvhw *InstancePtr, const char* InstanceName);
int XConvhw_Release(XConvhw *InstancePtr);
#endif

void XConvhw_Start(XConvhw *InstancePtr);
u32 XConvhw_IsDone(XConvhw *InstancePtr);
u32 XConvhw_IsIdle(XConvhw *InstancePtr);
u32 XConvhw_IsReady(XConvhw *InstancePtr);
void XConvhw_EnableAutoRestart(XConvhw *InstancePtr);
void XConvhw_DisableAutoRestart(XConvhw *InstancePtr);

void XConvhw_Set_inputWeights(XConvhw *InstancePtr, u32 Data);
u32 XConvhw_Get_inputWeights(XConvhw *InstancePtr);
void XConvhw_Set_inputBias(XConvhw *InstancePtr, u32 Data);
u32 XConvhw_Get_inputBias(XConvhw *InstancePtr);

void XConvhw_InterruptGlobalEnable(XConvhw *InstancePtr);
void XConvhw_InterruptGlobalDisable(XConvhw *InstancePtr);
void XConvhw_InterruptEnable(XConvhw *InstancePtr, u32 Mask);
void XConvhw_InterruptDisable(XConvhw *InstancePtr, u32 Mask);
void XConvhw_InterruptClear(XConvhw *InstancePtr, u32 Mask);
u32 XConvhw_InterruptGetEnabled(XConvhw *InstancePtr);
u32 XConvhw_InterruptGetStatus(XConvhw *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
