// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xconvhw.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XConvhw_CfgInitialize(XConvhw *InstancePtr, XConvhw_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XConvhw_Start(XConvhw *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvhw_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVHW_AXILITES_ADDR_AP_CTRL) & 0x80;
    XConvhw_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVHW_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XConvhw_IsDone(XConvhw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvhw_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVHW_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XConvhw_IsIdle(XConvhw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvhw_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVHW_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XConvhw_IsReady(XConvhw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvhw_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVHW_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XConvhw_EnableAutoRestart(XConvhw *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvhw_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVHW_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XConvhw_DisableAutoRestart(XConvhw *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvhw_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVHW_AXILITES_ADDR_AP_CTRL, 0);
}

void XConvhw_Set_inputWeights(XConvhw *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvhw_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVHW_AXILITES_ADDR_INPUTWEIGHTS_DATA, Data);
}

u32 XConvhw_Get_inputWeights(XConvhw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvhw_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVHW_AXILITES_ADDR_INPUTWEIGHTS_DATA);
    return Data;
}

void XConvhw_Set_inputBias(XConvhw *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvhw_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVHW_AXILITES_ADDR_INPUTBIAS_DATA, Data);
}

u32 XConvhw_Get_inputBias(XConvhw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvhw_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVHW_AXILITES_ADDR_INPUTBIAS_DATA);
    return Data;
}

void XConvhw_InterruptGlobalEnable(XConvhw *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvhw_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVHW_AXILITES_ADDR_GIE, 1);
}

void XConvhw_InterruptGlobalDisable(XConvhw *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvhw_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVHW_AXILITES_ADDR_GIE, 0);
}

void XConvhw_InterruptEnable(XConvhw *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XConvhw_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVHW_AXILITES_ADDR_IER);
    XConvhw_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVHW_AXILITES_ADDR_IER, Register | Mask);
}

void XConvhw_InterruptDisable(XConvhw *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XConvhw_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVHW_AXILITES_ADDR_IER);
    XConvhw_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVHW_AXILITES_ADDR_IER, Register & (~Mask));
}

void XConvhw_InterruptClear(XConvhw *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvhw_WriteReg(InstancePtr->Axilites_BaseAddress, XCONVHW_AXILITES_ADDR_ISR, Mask);
}

u32 XConvhw_InterruptGetEnabled(XConvhw *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XConvhw_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVHW_AXILITES_ADDR_IER);
}

u32 XConvhw_InterruptGetStatus(XConvhw *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XConvhw_ReadReg(InstancePtr->Axilites_BaseAddress, XCONVHW_AXILITES_ADDR_ISR);
}

